### PR TITLE
fix example for hexadecimal escape

### PR DESCRIPTION
**Pull request by bergus**
Follow up to #34.
@anba I knew it, damn.

### CODE REVIEW

**Comment by benjamingr** [comment]
Thanks

**Comment by domenic** [comment]
This still doesn't make much sense. `new RegExp("\\u004" + "A").test("u004A") === false`.

**Comment by mathiasbynens** [comment]
I don’t understand the confusion.

```js
> RegExp('\\u004' + 'A').test('J')
true
```

This patch makes sure that:

```js
> RegExp('\\u004' + RegExp.escape('A')).test('J')
false
```

**Comment by mathiasbynens** [comment]
Comment updated.

**Comment by anba** [comment]
If it's required (or desirable) to prevent `RegExp('\\u004' + RegExp.escape('A'))` expanding to `RegExp('\\u004A')`, then you probably also want to make sure `RegExp('\\c' + RegExp.escape('G'))` does not expand to `RegExp('\\cG')`. That means not only `0-9A-Fa-f`, but actually `0-9A-Za-z_` needs to be escaped.

**Comment by bergus** [comment]
@anba Can you add that to #29, please? I didn't think `/\c/` alone was valid, but it seems to compile indeed (though I don't see what it matches).

**Comment by anba** [comment]
@bergus Added a comment to the other issue.

**Pull request merged**
