### PR TITLE
updates to EscapedChars.md

### PR DESCRIPTION
**Pull request by bergus**
as suggested in #31

### CODE REVIEW

**Comment by bergus** [comment]
Uh, wait, is the following behaviour (tested in my browser console) actually buggy?
```js
>>> new RegExp("\\u41" + "B").test("u41B")
false
>>> new RegExp("\\u41" + "B").test("\u041B")
true
```
If I append a non-hexadecimal character, it matches the literal letters (and treats `\u` as an *IdentityEscape*):
```js
>>> new RegExp("\\u41" + "B%").test("u41B%")
true
>>> new RegExp("\\u41" + "B%").test("\u041B%")
false
```

**Comment by domenic** [comment]
Chrome has some bugs in this area, so definitely test a few browsers.

**Comment by bergus** [comment]
The test above was in (old) Opera. But before testing browsers, I wanted to get a confirmation that I've correctly understood [the spec](http://www.ecma-international.org/ecma-262/6.0/#sec-patterns) and the first snippet demonstrates a bug.

**Comment by anba** [comment]
> But before testing browsers, I wanted to get a confirmation that I've correctly understood the spec and the first snippet demonstrates a bug?

The first snippet should give the following output (*):
```javascript
js> new RegExp("\\u41" + "B").test("u41B")
true
js> new RegExp("\\u41" + "B").test("\u041B")
false
```

For Unicode enabled RegExps (or implementations without support for extension "B.1.4 Regular Expressions Patterns"), `new RegExp("\\u41" + "B")` throws a SyntaxError.

(*): Also tested in Edge, V8, JavaScriptCore, Nashorn and SpiderMonkey

**Comment by benjamingr** [comment]
Thanks @bergus !

**Pull request merged**
